# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911623f6f60515e1f0a4a0b75631000fbbd7f804a0966f0194b5295c623e0161705c304e1ea5d9709d4c704f6d6155ab2cda72eb2a9de7adb3167a74ba0afaaa

test:
  secret_key_base: d66ccc21e2152052fc8feb606cdd2a08a841a961fe7aa60452e5eaa4e9b37308c4466e23c4f3cbcea75e038b8c7b16edb2bc85ba250c2d4f93d7bc8e1c7c83e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
